### ISSUE TITLE
Data preprocessing pipeline is not reproducible

### ISSUE THREAD

**Issue by pietrolesci** [google-research/schema-guided-dialogue#5]
Hi there,

I am trying to reproduce the data preprocessing pipeline but due to missing files it is currently not possible. Is it possible to include a link to the preprocessed data itself?

Thanks,
Pietro

**Comment by abhirast** [comment]
We just added the processing scripts for SDT. Sorry for the delay. Please feel free to reopen the issue if there are problems running it.

**Comment by pietrolesci** [comment]
Hi @abhirast, thanks lot for adding it. I'll take a look at it later today. Thanks for your attention!
